### ISSUE TITLE
Add scale with dpi feature

### ISSUE THREAD

**Issue by asutenshi** [lukeyou05/tacky-borders#16]
In glazeWM you can customize the scale along with the monitor resolution. The problem is that if a user has two monitors, one FullHD and the other 2560*1440 for example, the borders on the monitors will be completely different sizes. I attach screenshots
FullHD:
![Screenshot 2024-12-23 105424](https://github.com/user-attachments/assets/39c717c2-709e-4d1d-8a19-7e779ed77545)
2560*1440:
![Screenshot 2024-12-23 105445](https://github.com/user-attachments/assets/ed4e97bf-a80a-4fa2-88ed-3c3e0617ba8d)

**Comment by lukeyou05** [comment]
You could try the latest preview build here: https://github.com/lukeyou05/tacky-borders/releases/tag/v1.0.0-preview2
It doesn't automatically adjust for dpi when a window/border switches between monitors, but it should at least scale correctly on the initial monitor (I think).

**Comment by lukeyou05** [comment]
This issue should have been fixed in this commit: #19

You can try it out by using the latest artifact from the workflow runs page: https://github.com/lukeyou05/tacky-borders/actions
Or, if you want a direct link: https://github.com/lukeyou05/tacky-borders/actions/runs/12553380014/artifacts/2372894592
Let me know if it works!

**NOTE:** if you're using one of the v1.0.0 preview builds and are using animations, you may have to adjust your config.yaml because I changed the animations config format. Otherwise, if you're coming from v0.3.0, you should be good to go.
