### ISSUE TITLE
Similar project

### ISSUE THREAD

**Issue by 0xSolanaceae** [lukeyou05/tacky-borders#7]
There appears to be a pretty similar project here:
https://github.com/keifufu/cute-borders

I took a look at both of your code, and I like how you have the option to change the border width. Just wanted to make you aware of a similar project! Enjoy!

**Comment by lukeyou05** [comment]
Haha thank you! Our projects are actually totally different under the hood. Their implementation uses the native win32 API that exists for Windows 11, which is rather limited in customization and limits you to 1px thick borders. In order to get get thicker borders (and potentially gradients and animations in the future), my app draws the borders using Direct2D on new transparent windows, which then get overlaid on top of the actual window we want borders on.

**Comment by 0xSolanaceae** [comment]
Awesome! Very cool
